storage: ./storage

uplinks:
  npmjs:
    url: https://registry.npmjs.org/

packages:
  'eslint-plugin-avoid-jest-spy-on':
    access: $all
    publish: $anonymous
    proxy: npmjs
  '**':
    access: $all
    proxy: npmjs
